base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pay.urls")),
    path('api/v1/', include(('rest_framework.urls'), namespace='api')),
    path('auth/', include('djoser.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/payments/', include('payments.urls', namespace='payments')),
    path('api/accounts/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pay/urls.py
from django.urls import path
from . import views
from pay.views import GetAllPay,SearchPay
urlpatterns = [
 path("", views.index, name="index"),
 path("config/", views.pay_config, name="config"),
 path("pay/", views.pay_request, name="pay"),
 path("success/", views.success, name="success"),
 path("cancelled/", views.cancel, name="cancelled"),
 path('api/v1/get-all-pay/', GetAllPay.as_view(), name="get_all"),
 path('api/v1/search-pay/', SearchPay.as_view()),
]

pay_module/urls.py
from django.urls import path
from paypal.standard.ipn.models import PayPalIPN
from .views import index, show_product, show_cart, checkout, process_payment, payment_done, payment_canceled
from django.views.decorators.csrf import csrf_exempt

app_name = "app"
urlpatterns = [
    path('', index, name='index'),
    path('product/<int:product_id>/<slug:product_slug>', show_product, name='product_detail'),
    path('cart/', show_cart, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('paypal-ipn/', csrf_exempt(PayPalIPN), name='paypal-ipn'),
    path('process-payment/', process_payment, name='process_payment'),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
]

pay_module/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=191)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    slug = models.SlugField()
    description = models.TextField()


    def __str__(self):
        return self.name


class CartItem(models.Model):
    cart_id = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.product}:{self.product_id}"

    def update_quantity(self, quantity):
        self.quantity += quantity
        self.save()

    def total_cost(self):
        return self.quantity * self.price


class Order(models.Model):
    name = models.CharField(max_length=191)
    email = models.EmailField()
    postal_code = models.IntegerField()
    address = models.CharField(max_length=191)
    date = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.id}"

    def total_cost(self):
        return sum([ li.cost() for li in self.lineitem_set.all() ] )


class LineItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    quantity = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.product.name}:{self.id}"
    def cost(self):
        return self.price * self.quantity

pay_module/forms.py
from django import forms
from .models import Order


class CartForm(forms.Form):
    quantity = forms.IntegerField(initial='1')
    product_id = forms.IntegerField(widget=forms.HiddenInput)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super(CartForm, self).__init__(*args, **kwargs)


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('paid',)

        widgets = {
            'address': forms.Textarea(attrs={'row': 5, 'col': 8}),
        }

pay_module/views.py
from django.shortcuts import render, HttpResponse, redirect, \
    get_object_or_404, reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from .models import Product, Order, LineItem
from .forms import CartForm, CheckoutForm
from . import cart

# Create your views here.


def index(request):
    all_products = Product.objects.all()
    return render(request, "pay_module/index.html", {
                                    'all_products': all_products,
                                    })


def show_product(request, product_id, product_slug):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = CartForm(request, request.POST)
        if form.is_valid():
            request.form_data = form.cleaned_data
            cart.add_item_to_cart(request)
            return redirect('app:cart')

    form = CartForm(request, initial={'product_id': product.id})
    return render(request, 'pay_module/product_detail.html', {
                                            'product': product,
                                            'form': form,
                                            })


def show_cart(request):

    if request.method == 'POST':
        if request.POST.get('submit') == 'Update':
            cart.update_item(request)
        if request.POST.get('submit') == 'Remove':
            cart.remove_item(request)

    cart_items = cart.get_all_cart_items(request)
    cart_subtotal = cart.subtotal(request)
    return render(request, 'pay_module/cart.html', {
                                            'cart_items': cart_items,
                                            'cart_subtotal': cart_subtotal,
                                            })


def checkout(request):
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            o = Order(
                name = cleaned_data.get('name'),
                email = cleaned_data.get('email'),
                postal_code = cleaned_data.get('postal_code'),
                address = cleaned_data.get('address'),
            )
            o.save()

            all_items = cart.get_all_cart_items(request)
            for cart_item in all_items:
                li = LineItem(
                    product_id = cart_item.product_id,
                    price = cart_item.price,
                    quantity = cart_item.quantity,
                    order_id = o.id
                )

                li.save()

            cart.clear(request)

            request.session['order_id'] = o.id

            messages.add_message(request, messages.INFO, 'Order Placed!')
            return redirect('app:process_payment')


    else:
        form = CheckoutForm()
        return render(request, 'pay_module/checkout.html', {'form': form})



def process_payment(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)

    return render(request, 'pay_module/process_payment.html', {'order': order})


@csrf_exempt
def payment_done(request):
    return render(request, 'pay_module/payment_done.html')


@csrf_exempt
def payment_canceled(request):
    return render(request, 'pay_module/payment_cancelled.html')

pay_module/templates/pay_module/cart.html
{% extends 'shared/layout.html' %}

{% block title %}
    My Cart |
{% endblock %}

{% block body %}

    <h2>My Cart</h2>


    <table>
        <thead>
        <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Quantity</th>
            <th></th>
            <th></th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart_items %}
            <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.price }}</td>
                <td>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="text" name="quantity" value="{{ item.quantity }}">
                        <input type="hidden" name="item_id" value="{{ item.id }}">
                </td>
                <td>
                        <input type="submit" name="submit" value="Update">
                    </form>
                </td>
                <td>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="item_id" value="{{ item.id }}">
                        <input type="submit" name="submit" value="Remove">
                    </form>
                </td>
                <td>${{ item.total_cost }}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" style="text-align: right">Total</td>
                <td>${{ cart_subtotal }}</td>
            </tr>
            <tr>
                <td></td>
                <td colspan="4" style="text-align: right">
                    <a href="{% url 'app:index' %}" class="btn btn-primary">Continue Shopping</a>
                </td>
                    <td><a href="{% url 'app:checkout' %}" class="btn btn-primary">Checkout</a></td>

            </tr>
        </tfoot>
    </table>



{% endblock %}

pay_module/templates/pay_module/checkout.html
{% extends 'shared/layout.html' %}

{% block title %}
    Checkout |
{% endblock %}

{% block body %}

    <div class="container">
        <div class="row">

            <h2>Checkout</h2>

            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}


            <form action="" method="post">
                <table>
                    {% csrf_token %}
                    {{ form }}
                    <tr>
                        <td></td>
                        <td><input type="submit" value="Place Order"></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>

{% endblock %}

pay_module/templates/pay_module/index.html
{% extends 'shared/layout.html' %}

{% block title %}
    home_page
{% endblock %}

{% block body %}
     <div class="container">
        <div class="row">
            <h2>Available Products</h2>

            {% for product in all_products %}
                <div class="col-lg-4">
                    <h3><a href="{% url 'app:product_detail' product.id product.slug  %}">{{ product.name }}</a></h3>
                    <p>Price ${{ product.price }}</p>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

pay_module/templates/pay_module/payment_cancelled.html
{% extends 'shared/layout.html' %}


{% block body %}

    <h2>Payment cancelled.</h2>

{% endblock %}

pay_module/templates/pay_module/payment_done.html
{% extends 'shared/layout.html' %}

{% block title %}Make Payment{% endblock %}

{% block body %}
    <h2>
    your payment was successfully done .
    </h2>
{% endblock %}

pay_module/templates/pay_module/payment_success.html
{% extends "shared/layout.html" %}
{% block content %}
    <h1>Payment Successful!</h1>
{% endblock %}

pay_module/templates/pay_module/process_payment.html
{% extends 'shared/layout.html' %}


{% block body %}

    {% csrf_token %}

    <div class="center">
        <h3 class="donate">
            <div class="w3-card-4">

                <header class="w3-container w3-blue">
                    <h1>DONATE</h1>
                </header>

                <div class="w3-container">
                    <p>Donate for a great cause. Be a hero.</p>

                    <!-- PAYPAL BUTTONS HERE  -->
                            <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AYuyuKXE8vRd2urbTWNlWjaUHTznselQBoCfFEEmRzB3eN6kUxggOqb8fvnYUJHIWGsEuFN9ORFpore1"></script>

    <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Call your server to set up the transaction
            createOrder: function(data,actions) {
                return fetch('/demo/checkout/api/paypal/order/create/', {
                    method: 'post'
                }).then(function(res) {
                    return res.json();
                }).then(function(orderData) {
                    return orderData.id;
                });
            },

            // Call your server to finalize the transaction
            onApprove: function(data, actions) {
                return fetch('/demo/checkout/api/paypal/order/' + data.orderID + '/capture/', {
                    method: 'post'
                }).then(function(res) {
                    return res.json();
                }).then(function(orderData) {
                    // Three cases to handle:
                    //   (1) Recoverable INSTRUMENT_DECLINED -> call actions.restart()
                    //   (2) Other non-recoverable errors -> Show a failure message
                    //   (3) Successful transaction -> Show confirmation or thank you

                    // This example reads a v2/checkout/orders capture response, propagated from the server
                    // You could use a different API or structure for your 'orderData'
                    var errorDetail = Array.isArray(orderData.details) && orderData.details[0];

                    if (errorDetail && errorDetail.issue === 'INSTRUMENT_DECLINED') {
                        return actions.restart(); // Recoverable state, per:
                        // https://developer.paypal.com/docs/checkout/integration-features/funding-failure/
                    }

                    if (errorDetail) {
                        var msg = 'Sorry, your transaction could not be processed.';
                        if (errorDetail.description) msg += '\n\n' + errorDetail.description;
                        if (orderData.debug_id) msg += ' (' + orderData.debug_id + ')';
                        return alert(msg); // Show a failure message (try to avoid alerts in production environments)
                    }

                    // Successful capture! For demo purposes:
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    var transaction = orderData.purchase_units[0].payments.captures[0];
                    alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                    // Replace the above to show a success message within this page, e.g.
                    // const element = document.getElementById('paypal-button-container');
                    // element.innerHTML = '';
                    // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                    // Or go to another URL:  actions.redirect('thank_you.html');
                });
            }

        }).render('#paypal-button-container');
    </script>

                    <div id="paypal-button-container"></div>

                    <!-- Include the PayPal JavaScript SDK -->
                    <script
                        src="https://www.paypal.com/sdk/js?client-id=AYuyuKXE8vRd2urbTWNlWjaUHTznselQBoCfFEEmRzB3eN6kUxggOqb8fvnYUJHIWGsEuFN9ORFpore1">
                    </script>

                    <script>
                        // Render the PayPal button into #paypal-button-container
                        paypal.Buttons({

                            // Set up the transaction
                            createOrder: function (data, actions) {
                                return actions.order.create({
                                    purchase_units: [{
                                        amount: {
                                            value: '50'
                                        }
                                    }]
                                });
                            },

                            // Finalize the transaction
                            onApprove: function (data, actions) {
                                return actions.order.capture().then(function (details) {
                                    // Show a success message to the buyer
                                    alert('Transaction completed by ' + details.payer.name
                                        .given_name + '!');
                                });
                            }


                        }).render('#paypal-button-container');
                    </script>

                </div>

                <footer class="w3-container w3-blue">
                    <h5>&copy Professional Cipher</h5>
                </footer>

            </div>
        </h3>

    </div>

{% endblock %}

pay_module/templates/pay_module/product_detail.html
{% extends 'shared/layout.html' %}

{% block title %}
{{ product.name }}
{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">

            <p><a href="{% url 'app:index' %}">All Products </a> &gt;
                {{ product.name }}
            </p>

                <h2>{{ product.name }}</h2>
                <p>Price ${{ product.price }}</p>

                <form action="{% url 'app:product_detail' product.id product.slug %}" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Add to cart" class="btn btn-primary" >
                </form>

        </div>

    </div>

{% endblock %}