base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pay.urls")),
    path('api/v1/', include(('rest_framework.urls'), namespace='api')),
    path('auth/', include('djoser.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/payments/', include('payments.urls', namespace='payments')),
    path('api/accounts/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pay/urls.py
from django.urls import path
from . import views
from pay.views import GetAllPay,SearchPay
urlpatterns = [
 path("", views.index, name="index"),
 path("config/", views.pay_config, name="config"),
 path("pay/", views.pay_request, name="pay"),
 path("success/", views.success, name="success"),
 path("cancelled/", views.cancel, name="cancelled"),
 path('api/v1/get-all-pay/', GetAllPay.as_view(), name="get_all"),
 path('api/v1/search-pay/', SearchPay.as_view()),
]

pay_module/urls.py
from django.urls import path
from paypal.standard.ipn.models import PayPalIPN
from .views import index, show_product, show_cart, checkout, process_payment, payment_done, payment_canceled
from django.views.decorators.csrf import csrf_exempt

app_name = "app"
urlpatterns = [
    path('', index, name='index'),
    path('product/<int:product_id>/<slug:product_slug>', show_product, name='product_detail'),
    path('cart/', show_cart, name='cart'),
    path('checkout/', checkout, name='checkout'),
    path('paypal-ipn/', csrf_exempt(PayPalIPN), name='paypal-ipn'),
    path('process-payment/', process_payment, name='process_payment'),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
]

templates/shared/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


    <style>
        .w3-container {
            font-size: 14px;
        }

        .center {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>
<body>

<p>
    <a href="{% url 'app:index' %}">All Products</a> |
    <a href="{% url 'app:cart' %}">Cart: {{ cart_item_count }} item</a>
</p>

<body>
{% block body %}

{% endblock %}
</body>